### ISSUE TITLE
Fix the social-media icons to be more noticeable

### ISSUE THREAD

**Issue by davidhjones** [codethesouth/website#7]
Tyler suggested the social-media icons should be updated to be more noticeable.

**Comment by codewithtyler** [comment]
@davidhjones What do you think about this? When you hover over the circle (and the icon) the icon changes to white. I can change the color of the circle or the hover color to whatever you like.

I also updated the copyright notice so that it always says the current year.

![codethesouth_footer](https://cloud.githubusercontent.com/assets/2483249/15412532/e74c0998-1ded-11e6-938f-ede4a8fc88a0.PNG)

**Comment by davidhjones** [comment]
I like this a lot. What about Twitter? Have you played with having them all the same color - like your website implementation? That might be better than keeping the colors I have?

**Comment by codewithtyler** [comment]
Sure I can do that. I'll play with the colors and see what I can come up with.

**Comment by codewithtyler** [comment]
@davidhjones here's what it looks like now. When you hover over each circle the icon will turn white which makes it a lot more noticeable. What do you think?

<img width="607" alt="cts-footer-social" src="https://cloud.githubusercontent.com/assets/2483249/15588253/8b760654-2352-11e6-9b4d-529883f633c2.PNG">
